[package]
name = "rustring"
version = "0.1.0"
authors = ["wolf4ood <enrico.risa@gmail.com>", "<lavrin@gmail.com>"]
edition = "2024"


[dependencies]
macro_rules_attribute = "0.2.2"
smol = "2.0.2"
smol-macros = "0.1.1"
